//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democracy.UIForms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Democracy.UIForms.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string Add_New_User {
            get {
                return ResourceManager.GetString("Add New User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close session.
        /// </summary>
        public static string Close_session {
            get {
                return ResourceManager.GetString("Close session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Enter A Email.
        /// </summary>
        public static string Email_Error {
            get {
                return ResourceManager.GetString("Email Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Enter An Email.
        /// </summary>
        public static string Email_Error2 {
            get {
                return ResourceManager.GetString("Email Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password incorrect..
        /// </summary>
        public static string Email_or_password_error {
            get {
                return ResourceManager.GetString("Email or password error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email....
        /// </summary>
        public static string Email_Place {
            get {
                return ResourceManager.GetString("Email Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a city.
        /// </summary>
        public static string Error_City {
            get {
                return ResourceManager.GetString("Error City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a country.
        /// </summary>
        public static string Error_Country {
            get {
                return ResourceManager.GetString("Error Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a Gender.
        /// </summary>
        public static string Error_Gender {
            get {
                return ResourceManager.GetString("Error Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an Occupation.
        /// </summary>
        public static string Error_Occupation {
            get {
                return ResourceManager.GetString("Error Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a Phone.
        /// </summary>
        public static string Error_Phone {
            get {
                return ResourceManager.GetString("Error Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a Stratum.
        /// </summary>
        public static string Error_Stratum {
            get {
                return ResourceManager.GetString("Error Stratum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the first name.
        /// </summary>
        public static string Fist_name_error {
            get {
                return ResourceManager.GetString("Fist name error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the last name.
        /// </summary>
        public static string Last_name_error {
            get {
                return ResourceManager.GetString("Last name error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and the confirm do not match.
        /// </summary>
        public static string Not_match_password_error {
            get {
                return ResourceManager.GetString("Not match password error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password confirm.
        /// </summary>
        public static string Password_Confirm_Error {
            get {
                return ResourceManager.GetString("Password Confirm Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Enter A Password.
        /// </summary>
        public static string Password_Error {
            get {
                return ResourceManager.GetString("Password Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You password must be at mimimun 6 characters.
        /// </summary>
        public static string Password_Lengh_Error {
            get {
                return ResourceManager.GetString("Password Lengh Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Password....
        /// </summary>
        public static string Password_Place_Holder {
            get {
                return ResourceManager.GetString("Password Place Holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me in this device.
        /// </summary>
        public static string Remember_me_in_this_device {
            get {
                return ResourceManager.GetString("Remember me in this device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email.
        /// </summary>
        public static string Valid_Email {
            get {
                return ResourceManager.GetString("Valid Email", resourceCulture);
            }
        }
    }
}
